branches:
  only:
    - master
language: python
sudo: false
cache: pip
python:
  - 3.4
env:
  - DIOFANT_GROUND_TYPES=python MPMATH_NOGMPY=Y
addons:
  apt:
    packages:
      - libgmp-dev
      - libatlas-dev
      - libatlas-base-dev
      - liblapack-dev
      - gfortran
      - graphviz
matrix:
  include:
    - python: 3.4
      script:
        - python setup.py test --cov -m 'not slow and not xfail'
      after_success:
        - codecov
    - python: 3.4
      install:
        - travis_wait pip install .[exports,plot,interactive,gmpy]
        - pip install flake8 sphinx numpydoc pytest-cov sphinx_rtd_theme
      script:
        - python setup.py flake8
        - python setup.py test --cov -m 'slow and not xfail'
        - sphinx-build -W -b html docs build/sphinx/html
      after_success:
        - codecov
    - python: 3.4
      install:
        - travis_wait pip install .[exports,plot,interactive,gmpy]
        - pip install pytest-cov
      env:
        - DIOFANT_GROUND_TYPES=gmpy1
      script:
        - py.test --cov diofant diofant/polys
      after_success:
        - codecov
before_install:
  - pip install --upgrade pip 'setuptools<=19.4' pytest
  - pip install codecov
install:
  - travis_wait pip install .[exports,plot,interactive,gmpy]
before_script:
  - sh -e /etc/init.d/xvfb start
  - export DISPLAY=:99.0
script:
  - python setup.py test
notifications:
  email: false
