branches:
  only:
    - master
language: python
sudo: false
cache: pip
python:
  - 3.4
  - 3.5
addons:
  apt:
    packages:
      - libmpfr-dev
      - libgmp-dev
      - libatlas-dev
      - libatlas-base-dev
      - liblapack-dev
      - gfortran
      - graphviz
matrix:
  include:
    - python: 3.4
      script:
        - python setup.py test --cov -m 'not slow and not xfail'
      after_success:
        - codecov
    - python: 3.4
      script:
        - python setup.py test --cov -m 'slow and not xfail'
      after_success:
        - codecov
    - python: 3.4
      install:
        - pip install flake8 sphinx numpydoc pytest-cov sphinx_rtd_theme
        - travis_wait pip install .[exports,plot,interactive]
      script:
        - python setup.py flake8
        - sphinx-build -W -b html docs build/sphinx/html
        - python examples/all.py
        - py.test --cov diofant diofant/polys
      after_success:
        - codecov
before_install:
  - |
    mkdir -p $HOME/.local
    wget ftp://ftp.gnu.org/gnu/mpc/mpc-1.0.2.tar.gz
    tar xzvf mpc-1.0.2.tar.gz
    pushd mpc-1.0.2
    ./configure --prefix=$HOME/.local
    make all install
    popd
    export CPATH=$HOME/.local/include
    export LIBRARY_PATH=$HOME/.local/lib
    export LD_LIBRARY_PATH=$HOME/.local/lib
  - pip install --upgrade pip setuptools pytest
  - pip install codecov
install:
  - travis_wait pip install .[exports,plot,interactive,gmpy]
before_script:
  - sh -e /etc/init.d/xvfb start
  - export DISPLAY=:99.0
script:
  - python setup.py test
notifications:
  email: false
