language: python
dist: trusty
sudo: false
cache: pip
python:
  - 3.6
env:
  - SPLIT=1/13
  - SPLIT=2/13
  - SPLIT=3/13
  - SPLIT=4/13
  - SPLIT=5/13
  - SPLIT=6/13
  - SPLIT=7/13
  - SPLIT=8/13
  - SPLIT=9/13
  - SPLIT=10/13
  - SPLIT=11/13
  - SPLIT=12/13
  - SPLIT=13/13
addons:
  apt:
    packages:
      - libmpc-dev
      - libmpfr-dev
      - libgmp-dev
      - libatlas-dev
      - libatlas-base-dev
      - liblapack-dev
      - gfortran
      - graphviz
matrix:
  include:
    - python: 3.5
      env: COVERAGE='on' SELECT='not slow and not xfail' SPLIT='1/13'
    - python: 3.5
      env: COVERAGE='on' SELECT='not slow and not xfail' SPLIT='2/13'
    - python: 3.5
      env: COVERAGE='on' SELECT='not slow and not xfail' SPLIT='3/13'
    - python: 3.5
      env: COVERAGE='on' SELECT='not slow and not xfail' SPLIT='4/13'
    - python: 3.5
      env: COVERAGE='on' SELECT='not slow and not xfail' SPLIT='5/13'
    - python: 3.5
      env: COVERAGE='on' SELECT='not slow and not xfail' SPLIT='6/13'
    - python: 3.5
      env: COVERAGE='on' SELECT='not slow and not xfail' SPLIT='7/13'
    - python: 3.5
      env: COVERAGE='on' SELECT='not slow and not xfail' SPLIT='8/13'
    - python: 3.5
      env: COVERAGE='on' SELECT='not slow and not xfail' SPLIT='9/13'
    - python: 3.5
      env: COVERAGE='on' SELECT='not slow and not xfail' SPLIT='10/13'
    - python: 3.5
      env: COVERAGE='on' SELECT='not slow and not xfail' SPLIT='11/13'
    - python: 3.5
      env: COVERAGE='on' SELECT='not slow and not xfail' SPLIT='12/13'
    - python: 3.5
      env: COVERAGE='on' SELECT='not slow and not xfail' SPLIT='13/13'
    - python: 3.5
      env: COVERAGE='on' EXTRA='on'
      install:
        - travis_wait pip install .[exports,plot,interactive,develop,docs]
      script:
        - python setup.py flake8
        - sphinx-build -W -b html docs build/sphinx/html
        - sphinx-build -W -b linkcheck docs build/sphinx/linkcheck
        - cat build/sphinx/linkcheck/output.txt
        - py.test --cov diofant diofant/polys
    - python: 3.5
      env: COVERAGE='on' EXTRA='on' DIOFANT_GROUND_TYPES='gmpy'
      install:
        - travis_wait pip install .[exports,develop]
      script:
        - py.test --cov diofant diofant/domains
    - stage: deploy
      script: skip
      deploy:
        provider: pypi
        user: skirpichev
        password:
          secure: "OCi5YeQKvjr62Yzg1Bq9/xzIVDJSlr3q3YICp/gfnoPxTmiOiOug/QSM0rxl929Rb9hvf/QuNI6bpkPs0lz2roXa0PdJ2pdoNOm5Md2e43htbMRfH54YS98QDxL+gwasr327iGLi++avxF3N+vSyWboJLkSydDDlVhB7k/t57Ig="
        distributions: "sdist bdist_wheel"
        server: https://pypi.python.org/pypi
        on:
          tags: true
before_install:
  - pip install --upgrade pip setuptools pytest codecov
install:
  - travis_wait pip install .[exports,plot,interactive,gmpy]
before_script:
  - sh -e /etc/init.d/xvfb start
  - export DISPLAY=:99.0
script:
  - |
    if [ -n "${COVERAGE}" ]; then
      python setup.py test --addopts "--cov diofant -m \"${SELECT}\" --split=${SPLIT}"
    else
      python setup.py test --addopts "--split=${SPLIT}"
    fi
after_success: test -n "${COVERAGE}" && codecov
notifications:
  email: false
