language: python
env:
  matrix:
  - TEST_DOCTESTS="true" FASTCACHE="false"
  - SPLIT="1/2"
  - SPLIT="2/2"
python:
  - 2.7
  - 3.4
matrix:
  include:
    - python: 2.7
      env:
        - TEST_EXTRA="true" TEST_PEP="true"
    - python: 3.4
      env:
        - TEST_EXTRA="true" TEST_PEP="true"
    - python: "pypy3"
      env:
        - TEST_DOCTESTS="true"
        - FASTCACHE="false"
    - python: "pypy3"
      env:
        - SPLIT="1/2"
        - FASTCACHE="false"
    - python: 2.7
      env: TEST_SPHINX="true" FASTCACHE="false"
    - python: 2.7
      env:
        - TEST_SLOW="true"
        - SPLIT="1/2"
    - python: 2.7
      env:
        - TEST_SLOW="true"
        - SPLIT="2/2"
    - python: 3.4
      env:
        - TEST_SLOW="true"
        - SPLIT="1/2"
    - python: 3.4
      env:
        - TEST_SLOW="true"
        - SPLIT="2/2"
  allow_failures:
    - python: "pypy3"
      env:
        - SPLIT="2/2"
        - FASTCACHE="false"
before_install:
  - if [[ "${FASTCACHE}" != "false" ]]; then
      pip install fastcache;
    fi
  - if [[ "${TEST_SPHINX}" == "true" ]]; then
      sudo apt-get update;
      sudo apt-get install --no-install-recommends graphviz inkscape texlive texlive-xetex texlive-fonts-recommended texlive-latex-extra lmodern docbook2x;
      pip install "sphinx==1.2.2";
      pip install "numpydoc==0.5";
    fi
  - if [[ "${TEST_EXTRA}" == "true" ]]; then
      sudo apt-get update;
      sudo apt-get -qq install libgmp-dev libatlas-dev libatlas-base-dev liblapack-dev gfortran;
      pip install "numpy==1.7.1";
      pip install "scipy==0.12.0";
      pip install --allow-external "matplotlib==1.2.1";
      pip install "gmpy==1.16";
      pip install "Theano==0.6";
    fi
  - if [[ "${TEST_SAGE}" == "true" ]]; then
      sudo apt-add-repository -y ppa:aims/sagemath;
      sudo apt-get update;
      sudo apt-get install sagemath-upstream-binary;
    fi
  - if [[ "${TEST_PEP}" == "true" ]]; then
      pip install "pep8==1.6.2";
    fi
  - pip install "pytest==2.7.0"
install:
  - if [[ "${TEST_SAGE}" != "true" ]]; then
      python setup.py install;
    fi
script:
  - if [[ "${TEST_PEP}" == "true" ]]; then
      pep8;
    fi
  - bin/test_travis.sh
notifications:
  email: false
