language: python
sudo: false
cache: pip
python:
  - 3.4
  - 3.5
addons:
  apt:
    packages:
      - libmpfr-dev
      - libgmp-dev
      - libatlas-dev
      - libatlas-base-dev
      - liblapack-dev
      - gfortran
      - graphviz
matrix:
  include:
    - python: 3.4
      env: COVERAGE='on' SELECT='not slow and not xfail'
    - python: 3.4
      env: COVERAGE='on' SELECT='slow and not xfail'
    - python: 3.4
      env: COVERAGE='on' EXTRA='on'
      install:
        - travis_wait pip install .[exports,plot,interactive,develop,docs]
      script:
        - python setup.py flake8
        - sphinx-build -W -b html docs build/sphinx/html
        - python examples/all.py
        - py.test --cov diofant diofant/polys
      after_success: codecov
before_install:
  - |
    mkdir -p $HOME/.local
    wget ftp://ftp.gnu.org/gnu/mpc/mpc-1.0.2.tar.gz
    tar xzvf mpc-1.0.2.tar.gz
    pushd mpc-1.0.2
    ./configure --prefix=$HOME/.local
    make all install
    popd
    export CPATH=$HOME/.local/include
    export LIBRARY_PATH=$HOME/.local/lib
    export LD_LIBRARY_PATH=$HOME/.local/lib
  - pip install --upgrade pip setuptools pytest codecov
install:
  - travis_wait pip install .[exports,plot,interactive,gmpy]
before_script:
  - sh -e /etc/init.d/xvfb start
  - export DISPLAY=:99.0
script:
  - |
    if [ -n "${COVERAGE}" ]; then
      python setup.py test --addopts "--cov diofant -m \"${SELECT}\""
    else
      python setup.py test
    fi
after_success: test -n "${COVERAGE}" && codecov
deploy:
  provider: pypi
  user: skirpichev
  password:
    secure: "OCi5YeQKvjr62Yzg1Bq9/xzIVDJSlr3q3YICp/gfnoPxTmiOiOug/QSM0rxl929Rb9hvf/QuNI6bpkPs0lz2roXa0PdJ2pdoNOm5Md2e43htbMRfH54YS98QDxL+gwasr327iGLi++avxF3N+vSyWboJLkSydDDlVhB7k/t57Ig="
  distributions: "sdist bdist_wheel"
  server: https://pypi.python.org/pypi
  on:
    python: 3.4
    condition: -z "${COVERAGE}"
    tags: true
notifications:
  email: false
