language: python
env:
  matrix:
  - TEST_DOCTESTS="true"
  - SPLIT="1/2"
  - SPLIT="2/2"
  - TEST_EXTRA="true" TEST_PEP="true"
  - TEST_SLOW="true" SPLIT="1/2"
  - TEST_SLOW="true" SPLIT="2/2"
python:
  - 2.7
  - 3.4
matrix:
  include:
    - python: 2.7
      env:
        - TEST_SPHINX="true"
    - python: 2.7
      env:
        - TEST_SAGE="true"
    - python: "pypy3"
      env:
        - TEST_DOCTESTS="true"
    - python: "pypy3"
      env:
        - SPLIT="1/2"
    - python: "pypy3"
      env:
        - SPLIT="2/2"
  allow_failures:
    - python: 2.7
      env:
        - TEST_SAGE="true"
before_install:
  - if [[ "${TEST_SPHINX}" == "true" ]]; then
      sudo apt-get update;
      sudo apt-get install --no-install-recommends graphviz inkscape texlive texlive-xetex texlive-fonts-recommended texlive-latex-extra lmodern docbook2x;
      pip install sphinx==1.2.2 numpydoc==0.5 sphinx_rtd_theme;
    fi
  - if [[ "${TEST_EXTRA}" == "true" ]]; then
      sudo apt-get update;
      sudo apt-get -qq install libgmp-dev libatlas-dev libatlas-base-dev liblapack-dev gfortran;
      travis_wait 30 pip install numpy==1.7.1 scipy==0.12.0 gmpy==1.16 Theano==0.6;
      travis_wait 30 pip install --allow-external matplotlib==1.2.1;
    fi
  - if [[ "${TEST_SAGE}" == "true" ]]; then
      sudo apt-add-repository -y ppa:aims/sagemath;
      sudo apt-get update;
      travis_wait 30 sudo apt-get install sagemath-upstream-binary;
    fi
  - if [[ "${TEST_PEP}" == "true" ]]; then
      pip install pep8==1.6.2;
    fi
  - pip install pytest==2.7.0
  - if [[ "${TRAVIS_PYTHON_VERSION}" == "2.7" ]]; then
      pip install pytest-cov coveralls --use-mirrors;
    fi
install:
  - if [[ "${TEST_SAGE}" != "true" ]]; then
      python setup.py install;
    fi
script:
  - if [[ "${TEST_PEP}" == "true" ]]; then
      pep8;
    fi
  - travis_wait 50 bin/test_travis.sh
after_success:
  - if [[ "${TRAVIS_PYTHON_VERSION}" == "2.7" ]]; then
      coveralls;
    fi
notifications:
  email: false
